export const SIZES = {
  REQUEST_ID: 8,
  DB_ID: 8,
  COMMAND: 1,
  OP_COUNT: 4,
  OP_TYPE: 1,
  COLLECTION_LEN: 2,
  DOC_ID: 8,
  PATCH_OPS_LEN: 4,
  PAYLOAD_LEN: 4,
} as const;

export const MAX_FRAME_SIZE = 16 * 1024 * 1024;

export const FRAME_OVERHEAD =
  SIZES.REQUEST_ID + SIZES.DB_ID + SIZES.COMMAND + SIZES.OP_COUNT;

export const OP_OVERHEAD = SIZES.OP_TYPE + SIZES.DOC_ID + SIZES.PAYLOAD_LEN;

export const RESPONSE_OVERHEAD = SIZES.REQUEST_ID + 1 + 4;

export const STATS_SIZE = 40;
